name: ✅Build And Test

on:
  push:
    branches: [ main, feature/** ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      #      max-parallel: 3
      matrix: # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python-version: [ "3.8","3.9","3.10","3.11" ]
    steps:
      - uses: actions/checkout@v3

      - name: ✅Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: ✅Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

      - name: ✅Test
        run: |
          python -m unittest tests.test_package
